import spacy

NLP = spacy.load("en_core_web_sm")
NER = NLP.get_pipe("ner")

# example texts to train the NER on
TRAIN_DATA = [
    (
    "Infectious neonatal conjunctivitis is typically contracted during vaginal delivery from exposure to bacteria from the birth canal.",
    {"entities": [(11, 33, "DIS")]}),
    (
    "An exanthem that is characterized by a diffuse, reddened, blanchable, finely papular, sandpaper like rash due to infection by group A streptococcus and the production of an erythrogenic toxin. ",
    {"entities": [(3, 10, "DIS")]}, {"entities": [(112, 127, "KEYWORD")]}, {"entities": [(154, 171, "KEYWORD")]}),
    ("Experts have identified many types of gastritis and gastropathy, which have different causes.",
     {"entities": [(38, 46, "DIS")]}, {"entities": [(52, 62, "DIS")]}),
    (
    "Before the introduction of the Hib vaccine in 1985,[4] Haemophilus meningitis was the leading cause of bacterial meningitis in children under the age of five",
    {"entities": [(55, 76, "DIS")]}, {"entities": [(31, 41, "KEYWORD")]}, {"entities": [(103, 122, "DIS")]}),
    ("The two most common types of meningococcal infections are meningitis and septicemia.",
     {"entities": [(29, 52, "DIS")]}, {"entities": [(58, 67, "DIS")]}, {"entities": [(73, 83, "DIS")]}),
    ("This condition is a life-threatening complication of syphilis infection.", {"entities": [(53, 60, "DIS")]}),
    ("The patient was diagnosed with cancer and started chemotherapy immediately", {"entities": [(31, 36, "DIS")]}, {"entities": [(50, 61, "KEYWORD")]} ),
    ("She suffers from diabetes and manages her blood sugar levels through medication and a controlled diet.",
     {"entities": [(17, 24, "DIS")]}, {"entities": [(42, 52, "KEYWORD")]}),
    ("The child was hospitalized with symptoms of pneumonia, including a high fever and difficulty breathing.",
     {"entities": [(44, 52, "DIS")]}),
    ("The doctor prescribed antibiotics to treat the patient's strep throat infection.",
     {"entities": [(57, 79, "DIS")]}),
    ("She experienced severe migraines and sought medical advice to find appropriate treatment options.",
     {"entities": [(23, 31, "DIS")]}),
    ( "The elderly man has been living with Parkinson's disease for over a decade and manages his symptoms with medication.",
    {"entities": [(23, 37, "DIS")]}),
    ("He was diagnosed with asthma and uses an inhaler to manage his respiratory symptoms",
     {"entities": [(22, 27, "DIS")]}),
    ("The study focused on understanding the genetic factors contributing to Alzheimer's disease progression in a cohort of elderly individuals.",
     {"entities": [(71, 89, "DIS")]}),
    ("Researchers discovered a novel mutation in the BRCA1 gene that is associated with an increased risk of developing breast cancer.",
     {"entities": [(47, 51, "KEYWORD")]}, {"entities": [(115, 127, "DIS")]})
    ("The team conducted a clinical trial to evaluate the efficacy of a new immunotherapy drug in patients with metastatic melanoma.",
     {"entities": [(106, 124, "DIS")]}),
    ( "Scientists identified a specific gene variant that confers susceptibility to type 2 diabetes by impairing insulin secretion.",
     {"entities": [(77, 91, "DIS")]}, {"entities": [(105, 111, "KEYWORD")]}),
( "A study investigated the molecular mechanisms underlying Parkinson's disease pathology and identified potential therapeutic targets.",
     {"entities": [(57, 75, "DIS")]}),
( "The patient was diagnosed with Crohn's disease, and a colonoscopy revealed characteristic inflammation and ulcers in the intestines.",
     {"entities": [(31, 45, "DIS")]}),
( "Researchers conducted a population-based study to assess the prevalence and risk factors of cardiovascular disease in a diverse cohort.",
     {"entities": [(92, 113, "DIS")]}),
( "A genetic study identified a rare mutation in the SCN1A gene as the cause of Dravet syndrome, a severe form of childhood epilepsy.",
     {"entities": [(50, 54, "KEYWORD")]}, {"entities": [(77, 91, "DIS")]}, {"entities": [(122, 129, "DIS")]}),
( "Scientists investigated the role of neuroinflammation in the pathogenesis of multiple sclerosis using a mouse model.",
     {"entities": [(36, 52, "KEYWORD")]},{"entities": [(77, 94, "DIS")]}),
( "The study identified a link between chronic inflammation and the development of rheumatoid arthritis through the dysregulation of immune responses.",
     {"entities": [(36, 55, "KEYWORD")]},{"entities": [(80, 99, "DIS")]}),
( "A genome-wide association study revealed several genetic loci associated with an increased risk of developing schizophrenia.",
     {"entities": [(110, 122, "DIS")]}),
( "Scientists conducted a clinical trial to evaluate the efficacy and safety of a novel drug for the treatment of advanced stage lung cancer.",
     {"entities": [(126, 136, "DIS")]}),
( "The patient presented with symptoms indicative of systemic lupus erythematosus, including joint pain, skin rashes, and renal involvement.",
     {"entities": [(50, 77, "DIS")]}),
( "A study identified a mutation in the CFTR gene as the underlying cause of cystic fibrosis, a life-threatening genetic disorder affecting the lungs and digestive system.",
     {"entities": [(37, 40, "KEYWORD")]}, {"entities": [(74, 88, "DIS")]}),
( "Researchers investigated the molecular pathways involved in the progression of pancreatic cancer and identified potential therapeutic targets.",
     {"entities": [(79, 95, "DIS")]}),
( "The study aimed to elucidate the mechanisms of drug resistance in malaria parasites and develop strategies to overcome this challenge.",
     {"entities": [(66, 72, "DIS")]}),
( "A comprehensive meta-analysis revealed a significant association between elevated blood pressure levels and the risk of cardiovascular diseases, including stroke and coronary artery disease.",
     {"entities": [(155, 160, "KEYWORD")]},{"entities": [(166, 188, "KEYWORD")]},{"entities": [(120, 143, "DIS")]}),
( "A vaginitis that is characterized by a grayish vaginal discharge usually of foul odor and the presence of Gardnerella vaginalis.",
     {"entities": [(106, 126, "KEYWORD")]},{"entities": [(2, 10, "DIS")]}),
( "People can become ill with campylobacteriosis by eating contaminated food, drinking contaminated water, or having contact with infected animals.",
     {"entities": [(26, 44, "DIS")]}),
( "Chlamydia, or more specifically a chlamydia infection, is a sexually transmitted infection caused by the bacterium Chlamydia trachomatis.[",
     {"entities": [(34, 52, "DIS")]},{"entities": [(0, 8, "DIS")]}),
( "Rheumatic fever is a disease that may develop after an infection with group A streptococcus bacteria (such as strep throat or scarlet fever)",
     {"entities": [(110, 121, "DIS")]},{"entities": [(126, 138, "DIS")]},{"entities": [(76, 99, "KEYWORD")]},{"entities": [(0, 14, "DIS")]}),
( "The classic symptom of chickenpox is an uncomfortable, itchy rash.",
     {"entities": [(23, 32, "DIS")]}),
( "Infectious mononucleosis (IM, mono), also known as glandular fever, is an infection usually caused by the Epstein–Barr virus (EBV)",
     {"entities": [(51, 65, "DIS")]},{"entities": [(106, 123, "KEYWORD")]},{"entities": [(0, 23, "DIS")]}),
( "The normal and most successful mode of rabies virus transmission is via the bite of a rabid animal.",
     {"entities": [(39, 51, "DIS")]}),
( ,
     {"entities": [(22, 27, "DIS")]}),
( ,
     {"entities": [(22, 27, "DIS")]}),
( ,
     {"entities": [(22, 27, "DIS")]}),
( ,
     {"entities": [(22, 27, "DIS")]}),
( ,
     {"entities": [(22, 27, "DIS")]}),
( ,
     {"entities": [(22, 27, "DIS")]}),
( ,
     {"entities": [(22, 27, "DIS")]}),
( ,
     {"entities": [(22, 27, "DIS")]}),
( ,
     {"entities": [(22, 27, "DIS")]}),
( ,
     {"entities": [(22, 27, "DIS")]}),
( ,
     {"entities": [(22, 27, "DIS")]}),
( ,
     {"entities": [(22, 27, "DIS")]}),
( ,
     {"entities": [(22, 27, "DIS")]}),
( ,
     {"entities": [(22, 27, "DIS")]}),
( ,
     {"entities": [(22, 27, "DIS")]}),
( ,
     {"entities": [(22, 27, "DIS")]}),
( ,
     {"entities": [(22, 27, "DIS")]}),

    ("He was diagnosed with Alzheimer's disease, and his family sought support from a local caregiver's association.",
     {"entities": [(22, 40, "DIS")]}),

]

raw_text = "Thanks to its safety and accessibility, magnetic resonance imaging (MRI) is extensively used in clinical " \
           "routine and research field, largely contributing to our understanding of the pathophysiology of " \
           "neurodegenerative disorders such as Alzheimer’s disease (AD). "
text1 = NLP(raw_text)
